###

GET http://localhost:3000/post
###

GET http://localhost:3000/post/6226100286d80c64c2ae54c1

###

GET http://localhost:3000/post?sender=Shalom


###

POST http://localhost:3000/post
Content-Type: application/json

{
    "message" :"1234 Try ",
    "sender" :"Shalom"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" :"ohad4@gmail.com ",
    "password" :"password"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" :"ohad1@gmail.com ",
    "password" :"password"
}